"""Add missing columns to comentarios table

Revision ID: 2a84022ee0f4
Revises: 316b137f85fc
Create Date: 2025-09-26 00:03:50.124416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a84022ee0f4'
down_revision: Union[str, Sequence[str], None] = '316b137f85fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comentarios', sa.Column('id_comentario_padre', sa.UUID(), nullable=True))
    op.add_column('comentarios', sa.Column('menciones', sa.TEXT(), nullable=True))
    op.create_foreign_key(op.f('comentarios_id_comentario_padre_fkey'), 'comentarios', 'comentarios', ['id_comentario_padre'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('comentarios_id_comentario_padre_fkey'), 'comentarios', type_='foreignkey')
    op.drop_column('comentarios', 'menciones')
    op.drop_column('comentarios', 'id_comentario_padre')
    # ### end Alembic commands ###
