"""add_historial_asistencia_table

Revision ID: 37f4e9501cde
Revises: ed7459a38574
Create Date: 2025-08-25 10:57:42.726006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37f4e9501cde'
down_revision: Union[str, Sequence[str], None] = 'ed7459a38574'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historialasistencia',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_inscripcion_usuario', sa.UUID(), nullable=False),
    sa.Column('id_inscripcion_publicacion', sa.UUID(), nullable=False),
    sa.Column('id_verificador', sa.UUID(), nullable=False),
    sa.Column('codigo_qr_data', sa.Text(), nullable=False),
    sa.Column('estado_verificacion', sa.Enum('pendiente', 'verificado', 'cancelado', name='estadoverificacionqrenum'), nullable=False),
    sa.Column('fecha_verificacion', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ubicacion_verificacion_lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('ubicacion_verificacion_lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('notas_verificacion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_inscripcion_publicacion'], ['publicaciones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_inscripcion_usuario'], ['usuarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_verificador'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('notificaciones')
    op.drop_constraint(op.f('comentarios_id_comentario_padre_fkey'), 'comentarios', type_='foreignkey')
    op.drop_column('comentarios', 'id_comentario_padre')
    op.drop_column('comentarios', 'menciones')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comentarios', sa.Column('menciones', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('comentarios', sa.Column('id_comentario_padre', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('comentarios_id_comentario_padre_fkey'), 'comentarios', 'comentarios', ['id_comentario_padre'], ['id'], ondelete='CASCADE')
    op.create_table('notificaciones',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id_usuario_destino', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id_usuario_origen', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id_publicacion', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('id_comentario', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('tipo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('mensaje', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('leida', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_comentario'], ['comentarios.id'], name=op.f('notificaciones_id_comentario_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_publicacion'], ['publicaciones.id'], name=op.f('notificaciones_id_publicacion_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario_destino'], ['usuarios.id'], name=op.f('notificaciones_id_usuario_destino_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario_origen'], ['usuarios.id'], name=op.f('notificaciones_id_usuario_origen_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('notificaciones_pkey'))
    )
    op.drop_table('historialasistencia')
    # ### end Alembic commands ###
