"""add rol field to usuarios table

Revision ID: 6376713d26a0
Revises: ab1128f7e9b2
Create Date: 2025-08-03 20:11:02.155989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6376713d26a0'
down_revision: Union[str, Sequence[str], None] = 'ab1128f7e9b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Crear el tipo enum primero
    tiporolenum = sa.Enum('usuario', 'admin', 'super_admin', name='tiporolenum')
    tiporolenum.create(op.get_bind())
    
    # Agregar la columna con el tipo enum
    op.add_column('usuarios', sa.Column('rol', tiporolenum, nullable=True, server_default='usuario'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'rol')
    
    # Eliminar el tipo enum
    tiporolenum = sa.Enum('usuario', 'admin', 'super_admin', name='tiporolenum')
    tiporolenum.drop(op.get_bind())
    # ### end Alembic commands ###
