"""fix_estadoamistadenum_bloqueada

Revision ID: 886b4cc4495a
Revises: a6f478346e99
Create Date: 2025-08-20 19:56:39.891653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '886b4cc4495a'
down_revision: Union[str, Sequence[str], None] = 'a6f478346e99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
