"""add_comentario_padre_and_menciones

Revision ID: 947fdf253398
Revises: e142c8fec4bd
Create Date: 2025-08-16 22:07:58.073666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '947fdf253398'
down_revision: Union[str, Sequence[str], None] = 'e142c8fec4bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notificaciones')
    op.add_column('comentarios', sa.Column('id_comentario_padre', sa.UUID(), nullable=True))
    op.add_column('comentarios', sa.Column('menciones', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'comentarios', 'comentarios', ['id_comentario_padre'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comentarios', type_='foreignkey')
    op.drop_column('comentarios', 'menciones')
    op.drop_column('comentarios', 'id_comentario_padre')
    op.create_table('notificaciones',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id_usuario_destino', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id_usuario_origen', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id_publicacion', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('id_comentario', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('tipo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('mensaje', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('leida', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_comentario'], ['comentarios.id'], name=op.f('notificaciones_id_comentario_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_publicacion'], ['publicaciones.id'], name=op.f('notificaciones_id_publicacion_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario_destino'], ['usuarios.id'], name=op.f('notificaciones_id_usuario_destino_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario_origen'], ['usuarios.id'], name=op.f('notificaciones_id_usuario_origen_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('notificaciones_pkey'))
    )
    # ### end Alembic commands ###
