"""add bloqueada to EstadoAmistadEnum

Revision ID: a6f478346e99
Revises: cc23c1b32e23
Create Date: 2025-08-20 19:40:37.118152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6f478346e99'
down_revision: Union[str, Sequence[str], None] = 'cc23c1b32e23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
