"""Crear todas las tablas

Revision ID: ab1128f7e9b2
Revises: 
Create Date: 2025-08-03 17:59:20.227226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab1128f7e9b2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre_usuario', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('genero', sa.Enum('Masculino', 'Femenino', 'Otro', name='tipogeneroenum'), nullable=True),
    sa.Column('foto_perfil_url', sa.Text(), nullable=True),
    sa.Column('biografia', sa.String(length=160), nullable=True),
    sa.Column('latitud', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitud', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('pais', sa.String(length=100), nullable=True),
    sa.Column('tema_preferido', sa.String(length=50), nullable=True),
    sa.Column('verificado', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_nombre_usuario'), 'usuarios', ['nombre_usuario'], unique=True)
    op.create_table('actividadesagenda',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_usuario', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_actividad', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('fecha_creacion', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('amistades',
    sa.Column('id_usuario1', sa.UUID(), nullable=False),
    sa.Column('id_usuario2', sa.UUID(), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'aceptada', 'rechazada', name='estadoamistadenum'), nullable=False),
    sa.Column('id_usuario_accion', sa.UUID(), nullable=False),
    sa.Column('fecha_creacion', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('id_usuario1 < id_usuario2', name='chk_user_order'),
    sa.ForeignKeyConstraint(['id_usuario1'], ['usuarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario2'], ['usuarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario_accion'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_usuario1', 'id_usuario2')
    )
    op.create_table('publicaciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_autor', sa.UUID(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('tipo', sa.Enum('Deporte', 'Social', 'Estudio', 'Cultural', 'Otro', name='tipopublicacionenum'), nullable=False),
    sa.Column('fecha_evento', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('privacidad', sa.Enum('publica', 'amigos', 'privada', name='tipoprivacidadenum'), nullable=False),
    sa.Column('media_url', sa.Text(), nullable=True),
    sa.Column('terminos_adicionales', sa.Text(), nullable=True),
    sa.Column('estado', sa.Enum('vigente', 'finalizado', 'cancelado', name='estadopublicacionenum'), nullable=False),
    sa.Column('fecha_creacion', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_autor'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comentarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_publicacion', sa.UUID(), nullable=False),
    sa.Column('id_autor', sa.UUID(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('fecha_creacion', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_autor'], ['usuarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_publicacion'], ['publicaciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eventosguardados',
    sa.Column('id_usuario', sa.UUID(), nullable=False),
    sa.Column('id_publicacion', sa.UUID(), nullable=False),
    sa.Column('fecha_guardado', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_publicacion'], ['publicaciones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_usuario', 'id_publicacion')
    )
    op.create_table('inscripciones',
    sa.Column('id_usuario', sa.UUID(), nullable=False),
    sa.Column('id_publicacion', sa.UUID(), nullable=False),
    sa.Column('fecha_inscripcion', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('estado_asistencia', sa.Enum('inscrito', 'asistio', 'no_asistio', name='estadoasistenciaenum'), nullable=False),
    sa.ForeignKeyConstraint(['id_publicacion'], ['publicaciones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_usuario', 'id_publicacion')
    )
    op.create_table('likes',
    sa.Column('id_usuario', sa.UUID(), nullable=False),
    sa.Column('id_publicacion', sa.UUID(), nullable=False),
    sa.Column('fecha_creacion', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_publicacion'], ['publicaciones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_usuario', 'id_publicacion')
    )
    op.create_table('rutas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_publicacion', sa.UUID(), nullable=False),
    sa.Column('latitud', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitud', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('etiqueta', sa.String(length=255), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_publicacion'], ['publicaciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rutas')
    op.drop_table('likes')
    op.drop_table('inscripciones')
    op.drop_table('eventosguardados')
    op.drop_table('comentarios')
    op.drop_table('publicaciones')
    op.drop_table('amistades')
    op.drop_table('actividadesagenda')
    op.drop_index(op.f('ix_usuarios_nombre_usuario'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
