"""create_notificaciones_table

Revision ID: cc23c1b32e23
Revises: 947fdf253398
Create Date: 2025-08-16 22:15:57.016124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc23c1b32e23'
down_revision: Union[str, Sequence[str], None] = '947fdf253398'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notificaciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_usuario_destino', sa.UUID(), nullable=False),
    sa.Column('id_usuario_origen', sa.UUID(), nullable=False),
    sa.Column('id_publicacion', sa.UUID(), nullable=True),
    sa.Column('id_comentario', sa.UUID(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('leida', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_comentario'], ['comentarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_publicacion'], ['publicaciones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario_destino'], ['usuarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario_origen'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notificaciones')
    # ### end Alembic commands ###
