"""remove rol field from usuarios table

Revision ID: e142c8fec4bd
Revises: 6376713d26a0
Create Date: 2025-08-03 20:26:30.519965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e142c8fec4bd'
down_revision: Union[str, Sequence[str], None] = '6376713d26a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'rol')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('rol', postgresql.ENUM('usuario', 'admin', 'super_admin', name='tiporolenum'), server_default=sa.text("'usuario'::tiporolenum"), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
